name: full

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: coursier/cache-action@v6
      - name: Set up Scala
        uses: olafurpg/setup-scala@v11
        with:
          java-version: adopt@1.11
      - name: Build application
        run: |
          sbt stage
          npm install
          npm run build
