name: ci

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: coursier/cache-action@v6
      - name: Set up Scala
        uses: olafurpg/setup-scala@v12
        with:
          java-version: adopt@1.11
      - name: Running tests
        run: |
          npm install
          sbt -v -J-Xmx4g compile scalafmtCheckAll headerCheck test:headerCheck test
